------=_Part_0_1145105632.1353005695468
Content-Type: application/xop+xml;charset=UTF-8;type="text/xml"
Content-Transfer-Encoding: 8bit
Content-ID: <cbe648b3-2055-413e-b8ed-877cdf0f2477>

<?xml version="1.0" encoding="UTF-8" ?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"/><soapenv:Body><tes:fooOwsmMsgProtection xmlns:tes="http://testOwsm">
    <!--Optional:
    --><arg0>string</arg0>
<Picture><xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href="cid:534475ae-bdab-4594-9f97-c09908bacfbd"/></Picture></tes:fooOwsmMsgProtection></soapenv:Body></soapenv:Envelope>
------=_Part_0_1145105632.1353005695468
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary
Content-ID: <534475ae-bdab-4594-9f97-c09908bacfbd>

My picture
------=_Part_0_1145105632.1353005695468--
