------=_Part_0_1145105632.1353005695468
Content-Id: <6e1e30fe-9874-43ff-a9d1-c02af3969f04>
Content-Type: application/xop+xml;charset=UTF-8;type="text/xml"
Content-Transfer-Encoding: binary

<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><tes:fooOwsmMsgProtection xmlns:tes="http://testOwsm">
    <!--Optional:
    --><arg0>string</arg0>
<Picture>TXkgcGljdHVyZQ==</Picture></tes:fooOwsmMsgProtection></soapenv:Body></soapenv:Envelope>
------=_Part_0_1145105632.1353005695468
Content-Id: <534475ae-bdab-4594-9f97-c09908bacfbd>
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

My picture
------=_Part_0_1145105632.1353005695468--