module client {
    requires java.xml.ws;

      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.schema_inline.server.jaxws;
    exports fromjava.schema_inline.client;
}
