module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.schema_inline.server.jaxws;
    exports fromjava.schema_inline.server;
}
