
package async.wsdl_hello_lit.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.12-09/15/2013 04:03 PM(snajper)-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Hello", targetNamespace = "urn:test", wsdlLocation = "file:/Users/snajper/work/sources/jaxws/ri/jaxws-unit/testcases/async/wsdl_hello_lit/server/hello_literal.wsdl")
public class Hello_Service
    extends Service
{

    private final static URL HELLO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(async.wsdl_hello_lit.server.Hello_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = async.wsdl_hello_lit.server.Hello_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/snajper/work/sources/jaxws/ri/jaxws-unit/testcases/async/wsdl_hello_lit/server/hello_literal.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/snajper/work/sources/jaxws/ri/jaxws-unit/testcases/async/wsdl_hello_lit/server/hello_literal.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLO_WSDL_LOCATION = url;
    }

    public Hello_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hello_Service() {
        super(HELLO_WSDL_LOCATION, new QName("urn:test", "Hello"));
    }

    /**
     * 
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort() {
        return super.getPort(new QName("urn:test", "HelloPort"), Hello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:test", "HelloPort"), Hello.class, features);
    }

}
