package com.sun.xml.ws.sdo.test;

import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.sun.xml.ws.sdo.test.helloSDO.MySDO;

/**
 * JAXWS-SDO client side proxy. This will be generated by the WSA tools.
 *  
 * @author shih-chang.chen@oracle.com
 */
@WebService(targetNamespace="http://oracle.j2ee.ws.jaxws.test/")
//@SchemaLocation("oracle/j2ee/ws/jaxws/test/MySDO.xsd")


public interface HelloSDO_ProxyInterface {
    
    @SOAPBinding(parameterStyle= SOAPBinding.ParameterStyle.BARE)
    public MySDO echoSDO(MySDO coo);
    
}

