module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.abstractimpl.jaxws;
    exports fromjava.abstractimpl;
}
