//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.03 at 05:01:03 PM CEST 
//


package com.oracle.xmlns.webservices.jaxws_databinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.ws.soap.AddressingFeature;
import java.lang.annotation.Annotation;

import static com.oracle.xmlns.webservices.jaxws_databinding.Util.nullSafe;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "addressing")
public class Addressing implements javax.xml.ws.soap.Addressing {

    @XmlAttribute(name = "enabled")
    protected Boolean enabled;

    @XmlAttribute(name = "required")
    protected Boolean required;

    public Boolean getEnabled() {
        return enabled();
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean getRequired() {
        return required();
    }

    public void setRequired(Boolean required) {
        this.required = required;
    }

    @Override
    public boolean enabled() {
        return nullSafe(enabled, true);
    }

    @Override
    public boolean required() {
        return nullSafe(required, false);
    }

    @Override
    public AddressingFeature.Responses responses() {
        return AddressingFeature.Responses.ALL;
    }

    @Override
    public Class<? extends Annotation> annotationType() {
        return javax.xml.ws.soap.Addressing.class;
    }
}
