module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports handler.context_wsdl_op.server.jaxws;
    exports handler.context_wsdl_op.server;
    exports handler.context_wsdl_op.common;
}
