module server {
    requires java.xml.ws;
      requires jdk.httpserver;
      requires java.logging; 

    // generated by WsimportTool
    exports custom.pkg;
    exports customization.external_exception_name.server;

}
