<?xml version="1.0" encoding="utf-8"?>
<definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="urn:test:rpclit:retailer"
    targetNamespace="urn:test:rpclit:retailer"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">
    <import
        namespace="urn:test:rpclit:retailer"
        location="definitions/retailer.wsdl"/>
    <types/>
    <service name="RetailerService">
        <port name="RetailerPort" binding="tns:RetailerSoapBinding">
            <soap:address location="http://localhost:8080/retailer"/>
        </port>
    </service>
</definitions>

