module server {
    requires java.xml.ws;
      requires jdk.httpserver;
      requires java.logging; 

    // generated by WsimportTool
    exports fromwsdl.rpclit_134.server;
    exports fromwsdl.rpclit_134.common;
}
