
package com.sun.xml.ws.client.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://echo.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Echo {


    /**
     * 
     * @param add
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResponse", targetNamespace = "http://echo.org/", partName = "addResponse")
    @Action(input = "http://echo.org/Echo/addRequest", output = "http://echo.org/Echo/addResponse")
    public int add(
        @WebParam(name = "add", targetNamespace = "http://echo.org/", partName = "add")
        NumbersRequest add);

    /**
     * 
     * @param addNumbersResponse
     * @param addNumbers
     */
    @WebMethod
    @Action(input = "http://echo.org/Echo/addNumbersRequest", output = "http://echo.org/Echo/addNumbersResponse")
    public void addNumbers(
        @WebParam(name = "addNumbers", targetNamespace = "http://echo.org/", partName = "addNumbers")
        NumbersRequest addNumbers,
        @WebParam(name = "addNumbersResponse", targetNamespace = "http://echo.org/", mode = WebParam.Mode.OUT, partName = "addNumbersResponse")
        Holder<Integer> addNumbersResponse);

    /**
     * 
     * @param echoString
     */
    @WebMethod
    @Action(input = "http://echo.org/Echo/echoStringRequest", output = "http://echo.org/Echo/echoStringResponse")
    public void echoString(
        @WebParam(name = "echoString", targetNamespace = "http://echo.org/", mode = WebParam.Mode.INOUT, partName = "echoString")
        Holder<String> echoString);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param echoHeaders
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "echoHeadersResponse", targetNamespace = "http://echo.org/", partName = "echoHeadersResponse", header = true)
    @Action(input = "http://echo.org/Echo/echoHeadersRequest", output = "http://echo.org/Echo/echoHeadersResponse")
    public String echoHeaders(
        @WebParam(name = "echoHeaders", targetNamespace = "http://echo.org/", mode = WebParam.Mode.INOUT, partName = "echoHeaders")
        Holder<String> echoHeaders,
        @WebParam(name = "arg1", targetNamespace = "http://echo.org/", header = true, partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://echo.org/", header = true, mode = WebParam.Mode.OUT, partName = "arg2")
        Holder<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "http://echo.org/", header = true, mode = WebParam.Mode.INOUT, partName = "arg3")
        Holder<String> arg3);

}
