module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.nillable_430.server.jaxws;
    exports fromjava.nillable_430.server;
}
