module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports bugs.jaxb274.jaxws;
    exports bugs.jaxb274;
}
