module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    export bugs.jaxb274.jaxws;
    export bugs.jaxb274;
}
