package async.wsdl_hello_lit_fault.server;

import javax.jws.WebService;
import javax.xml.ws.Holder;

/**
 * Impl class for interface generated by wscompile -import.
 * This class will overwrite the impl class generated by wscompile.
 */
@WebService(endpointInterface="async.wsdl_hello_lit_fault.server.Hello")
public class HelloService implements Hello {
    public HelloOutput hello(Hello_Type req) throws async.wsdl_hello_lit_fault.server.HelloFault{
        System.out.println("Hello_PortType_Impl received: " + req.getArgument() +
            ", " + req.getExtra());
        HelloOutput resp = new HelloOutput();
        resp.setArgument(req.getArgument());
        resp.setExtra(req.getExtra());
        System.out.println("Hello_PortType_Impl - before throwing HelloFault");
        HelloBodyFault myFault = new HelloBodyFault();
        myFault.setFaultMessage("throwing fault in hello4");
        throw new HelloFault("test for fault", myFault);

    }

    public void hello1(HelloType req, HelloType inHeader,
            Holder<HelloOutput> resp, Holder<HelloType> outHeader){
        HelloOutput out = new HelloOutput();
        out.setArgument(req.getArgument());
        out.setExtra(req.getExtra());
        resp.value = out;
        outHeader.value = inHeader;
    }

}
