//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-586 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.23 at 06:17:13 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:calculator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fromjava.jaxws563.server.types;
