/*
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * Hello_Impl.java
 *
 * Created on July 25, 2003, 10:37 AM
 */

package client.dispatch.wsdl_hello_lit_oneway.server;

import javax.jws.WebService;
import javax.jws.Oneway;



/**
 * Impl class for interface generated by wscompile -import.
 * This class will overwrite the impl class generated by wscompile.
 */
@WebService(name = "Hello", serviceName = "Hello_Service", endpointInterface="client.dispatch.wsdl_hello_lit_oneway.server.Hello")
public class Hello_PortType_Impl implements Hello {

    @Oneway
        public void hello(Hello_Type req)  {
        return;
    }

    @Oneway
        public void voidTest(VoidTest req) {
        return;
    }

    @Oneway
        public void echo(String message) {
        // Oneway methods should return response code before invoking
        // the endpoint. To test this, sleep() is required.
        try {
            Thread.sleep(10000);
        } catch (InterruptedException ie) {
        }
        if (!message.equals("Sun Microsystems")) {
            System.out.println("ERROR: echoTest failed! Expected \"Sun Microsystems\", received null!");
        }
        return;
    }

}
