module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports server.session_ignorecase_portable1.server.jaxws;
    exports server.session_ignorecase_portable1.server;
}
