module client {
    requires java.xml.ws;

    requires java.logging;
    requires java.rmi;

    // generated by WebServiceWrapperGenerator
    exports fromjava.webmethod_exclude1.jaxws;
    exports fromjava.webmethod_exclude1;
    exports fromjava.webmethod_exclude1.client;
}
