<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright 2003 Sun Microsystems, Inc. All rights reserved.
   SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->

<definitions name="SimpleTest" targetNamespace="http://simpletestservice.org/wsdl" xmlns:tns="http://simpletestservice.org/wsdl" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types/>
  <message name="SimpleEndpoint_alwaysThrowsWebServiceException"/>
  <message name="SimpleEndpoint_alwaysThrowsWebServiceExceptionResponse"/>
  <portType name="SimpleEndpoint">
    <operation name="alwaysThrowsWebServiceException">
      <input message="tns:SimpleEndpoint_alwaysThrowsWebServiceException"/>
      <output message="tns:SimpleEndpoint_alwaysThrowsWebServiceExceptionResponse"/></operation></portType>
  <binding name="SimpleEndpointBinding" type="tns:SimpleEndpoint">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="alwaysThrowsWebServiceException">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://simpletestservice.org/wsdl"/></input>
      <output>
        <soap:body use="literal" namespace="http://simpletestservice.org/wsdl"/></output>
    </operation>
  </binding>
  <service name="SimpleTest">
    <port name="SimpleEndpointPort" binding="tns:SimpleEndpointBinding">
      <soap:address location="http://localhost:8000/W2JRLR1016TestService/ws4ee_1/SimpleTest"/></port></service></definitions>
