<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.test.policy.ws.xml.sun.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://service.test.policy.ws.xml.sun.com/" name="TestServiceService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://service.test.policy.ws.xml.sun.com/" schemaLocation="TestService.xsd">
                </xsd:import>
        </xsd:schema>
    </types>
    <message name="echo">
        <part name="parameters" element="tns:echo">
             </part>
    </message>
    <message name="echoResponse">
        <part name="parameters" element="tns:echoResponse">
            </part>
    </message>
    <portType name="TestService">
        <operation name="echo">
            <input message="tns:echo">
                 </input>
            <output message="tns:echoResponse">
                </output>
        </operation>
    </portType>
    <binding name="TestServicePortBinding" type="tns:TestService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document">


        </soap:binding>
        <operation name="echo">
            <soap:operation soapAction="">
                </soap:operation>
            <input>
                <soap:body use="literal">
                   </soap:body>
            </input>
            <output>
                <soap:body use="literal">
                    </soap:body>
            </output>
        </operation>
    </binding>
    <service name="TestServiceService">
        <port name="TestServicePort" binding="tns:TestServicePortBinding">
            <soap:address location="http://localhost:8080/extern/TestServiceService">
                      

            </soap:address>
        </port>
    </service>
</definitions>