module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.dynamic_775.server.jaxws;
    exports fromjava.dynamic_775.server;
}
