
package com.sun.xml.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocService", targetNamespace = "http://performance.bea.com", wsdlLocation = "http://localhost:7001/DocService/DocService?WSDL")
public class DocService
    extends Service
{

    private final static URL DOCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sun.xml.ws.client.DocService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sun.xml.ws.client.DocService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/DocService/DocService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/DocService/DocService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCSERVICE_WSDL_LOCATION = url;
    }

    public DocService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocService() {
        super(DOCSERVICE_WSDL_LOCATION, new QName("http://performance.bea.com", "DocService"));
    }

    /**
     * 
     * @return
     *     returns DocServicePortType
     */
    @WebEndpoint(name = "DocServicePortTypePort")
    public DocServicePortType getDocServicePortTypePort() {
        return super.getPort(new QName("http://performance.bea.com", "DocServicePortTypePort"), DocServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocServicePortType
     */
    @WebEndpoint(name = "DocServicePortTypePort")
    public DocServicePortType getDocServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://performance.bea.com", "DocServicePortTypePort"), DocServicePortType.class, features);
    }

}
