module client {
    requires java.xml.ws;

      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.jaxb_annotation.jaxws;
    exports fromjava.jaxb_annotation;
    exports fromjava.jaxb_annotation.client;
}
