module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports epr.epr_webparam.server.jaxws;
    exports epr.epr_webparam.server;
}
