module server {
    requires java.xml.ws;
    requires jdk.httpserver;
    requires java.logging;

    // generated by WebServiceWrapperGenerator
    exports fromjava.handlerchain.common;
    exports fromjava.handlerchain.server;
}
