<?xml version="1.0" encoding="UTF-8"?>
<definitions
        xmlns:tns="http://echo.abstract.org/"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        targetNamespace="http://echo.abstract.org/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:types="http://echo.types.org/"
        name="RpcLitEndpoint">

    <types>
        <xs:schema>
            <xs:import namespace="http://echo.types.org/" schemaLocation="RpcLitEndpoint.xsd"/>
        </xs:schema>
    </types>

    <message name="echoIntegerResponse">
        <part type="types:num" name="return"></part>
    </message>

    <message name="echoInteger">
        <part type="types:num" name="arg0"></part>
    </message>

    <portType name="RpcLitIF">
        <operation name="echoInteger" parameterOrder="arg0">
            <input message="tns:echoInteger"></input>
            <output message="tns:echoIntegerResponse"></output>
        </operation>
    </portType>
    <!-- NOT_GENERATED -->
</definitions>

