package com.sun.xml.ws.sdo.test;


import java.util.List;

import javax.jws.WebService;

import com.sun.xml.ws.sdo.test.helloSDO.MySDO;

/**
 * JAXWS-SDO client side proxy. This should be generated by the tools.
 *  
 * @author shih-chang.chen@oracle.com
 */
@WebService(targetNamespace="http://oracle.j2ee.ws.jaxws.test/")
public interface HelloSDO_DocLitWrap {    
    public MySDO echoSDO(MySDO coo);
    public MySDO partI(MySDO coo, int i);
    public String returnS(MySDO coo);
    public int returnI(MySDO coo);           
    public List<String> testList1(List<MySDO> l);
    public List<String> testList2(List<String> l1, List<MySDO> l2);
    public String[] arrayList01(MySDO[] l);          
}
