//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-02/25/2009 05:47 AM(foreman)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.10 at 02:07:19 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://namespace2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fromjava.cr6940117.pak2.bean;
