
package fromwsdl.client_from_sei.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-05/14/2009 07:27 PM(jitu)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "urn:test")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//@XmlSeeAlso({
//    ObjectFactory.class
//})
public interface MyHello {


    /**
     * 
     * @param parameters
     * @return
     *     returns fromwsdl.client_from_sei.server.HelloResponse
     */
    @WebMethod(action = "urn:test:hello")
    @WebResult(name = "HelloResponse", targetNamespace = "urn:test:types", partName = "parameters")
    public MyHelloResponse hello(
        @WebParam(name = "Hello", targetNamespace = "urn:test:types", partName = "parameters")
        MyHello_Type parameters);

}
