module server {
    requires java.xml.ws;
      requires jdk.httpserver;
      requires java.logging; 

    // generated by WsimportTool
    exports customization.fully_qualified_service_name.server;

}
