module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports wsa.w3c.fromjava.addressing_required.server.jaxws;

}
