<definitions 
  name="HelloTest"
  targetNamespace="urn:test"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:types="urn:test:types"
  xmlns:tns="urn:test">
  
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:test:types" schemaLocation="hello.xsd"/>
    </xsd:schema>
  </types>

  <message name="HelloRequest">
    <part name="parameters" element="types:Hello"/>
  </message>
  
  <message name="MarshallTest_voidTest">
    <part name="parameters" element="types:VoidTest"/>
  </message>

  <portType name="Hello">
    <operation name="hello">
      <input message="tns:HelloRequest"/>
    </operation>  
    
    <!-- this is a regression test for bug 4823861 -->
    <operation name="voidTest">
      <input message="tns:MarshallTest_voidTest"/>
    </operation>
  </portType>
  
  <binding name="HelloBinding" type="tns:Hello">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="hello">
      <soap:operation soapAction="urn:test:hello"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>      
    <operation name="voidTest">
      <input>
        <soap:body use="literal"/></input>
      <soap:operation soapAction=""/>
    </operation>
  </binding>
    
  <service name="Hello">
    <port name="HelloPort" binding="tns:HelloBinding">
      <soap:address location="http://test.org/hello"/>
    </port>
  </service>
  
</definitions>
