
package com.sun.xml.ws.test.xbeandoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TypedXmlBeansDOC", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TypedXmlBeansDOC {


    /**
     * 
     * @param param1
     * @param countries
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getCountryName")
    @WebResult(name = "name", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCountryName", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.GetCountryName")
    @ResponseWrapper(localName = "getCountryNameResponse", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.GetCountryNameResponse")
    public String getCountryName(
//        @WebParam(name = "Countries", targetNamespace = "http://www.bea.com/wli/sb/transports/ejb/test/xbean")
        Countries countries,
//        @WebParam(name = "param1", targetNamespace = "http://www.openuri.org/")
        String param1);

    /**
     * 
     * @param param0
     * @param param1
     * @return
     *     returns com.sun.xml.ws.test.xbeandoc.CountryInfoType
     */
    @WebMethod(action = "http://www.openuri.org/getCountryInfo")
    @WebResult(name = "CountryInfoType", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCountryInfo", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.GetCountryInfo")
    @ResponseWrapper(localName = "getCountryInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.GetCountryInfoResponse")
    public CountryInfoType getCountryInfo(
        @WebParam(name = "param0", targetNamespace = "http://www.openuri.org/")
        String param0,
        @WebParam(name = "param1", targetNamespace = "http://www.openuri.org/")
        String param1);

    /**
     * 
     * @param param1
     * @param countries
     */
    @WebMethod(action = "http://www.openuri.org/addCountry")
    @RequestWrapper(localName = "addCountry", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.AddCountry")
    @ResponseWrapper(localName = "addCountryResponse", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.AddCountryResponse")
    public void addCountry(
//        @WebParam(name = "Countries", targetNamespace = "http://www.bea.com/wli/sb/transports/ejb/test/xbean", mode = WebParam.Mode.INOUT)
        Holder<Countries> countries,
//        @WebParam(name = "param1", targetNamespace = "http://www.openuri.org/")
        CountryInfoType param1);

    /**
     * 
     * @param param1
     * @param countries
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getCountryNameXml")
    @WebResult(name = "name", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCountryNameXml", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.GetCountryNameXml")
    @ResponseWrapper(localName = "getCountryNameXmlResponse", targetNamespace = "http://www.openuri.org/", className = "com.sun.xml.ws.test.xbeandoc.GetCountryNameXmlResponse")
    public String getCountryNameXml(
//        @WebParam(name = "Countries", targetNamespace = "http://www.bea.com/wli/sb/transports/ejb/test/xbean")
        Countries countries,
        @WebParam(name = "param1", targetNamespace = "http://www.openuri.org/")
        String param1);

}
