module server {
    requires java.xml.ws;
    requires jdk.httpserver;
    requires java.logging;
    requires java.rmi;

    // generated by WebServiceWrapperGenerator
    exports fromjava.seinoimpl_inherited.server.jaxws;
    exports fromjava.seinoimpl_inherited.server;
}
