module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports bugs.jaxws236.server.jaxws;
    exports bugs.jaxws236.server;
}
