<definitions targetNamespace="urn:test"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:tns="urn:test" 
             xmlns:types="urn:test:types" 
             xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:test:types" schemaLocation="test.xsd"/>
    </xsd:schema>
  </types>
  <message name="echoRequest">
    <part name="parameters" element="types:echo"/>
  </message>
  <message name="echoResponse">
    <part name="parameters" element="types:echoResponse"/>
  </message>
  <portType name="Hello">
    <operation name="echo">
      <input message="tns:echoRequest"/>
      <output message="tns:echoResponse"/>
    </operation>
  </portType>
  <binding name="HelloPortBinding" type="tns:Hello">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="echo">
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="HelloService">
    <port name="HelloPort" binding="tns:HelloPortBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
    </port>
  </service>
</definitions>
