module client {
    requires java.xml.ws;

      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports fromjava.cr6940117.pak2.jaxws;
    exports fromjava.cr6940117.pak2.bean;
    exports fromjava.cr6940117.pak2;
}
