module client {
    requires java.xml.ws;

      requires java.logging; 

    // generated by WsimportTool
    exports client.dispatch.header.doclit;
    exports client.dispatch.header.doclit.client;
}
