module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports dispatch.generate.client;
    exports bugs.jaxws620.server;
}
