module server {
    requires java.xml.ws;
     requires jdk.httpserver;
      requires java.logging; 

    // generated by WebServiceWrapperGenerator
    exports mtom.charset.server.jaxws;
    exports mtom.charset.server;
}
